name: ydokey
base: core20
version: '0.2.0'
summary: Convent key commands to raw keycodes for ydotool
description: |
  A simple command-line utility for Linux to convent key commands to raw keycodes which used in ydotool
contact: anton.maminov@gmai.com

grade: stable
confinement: strict

type: app
architectures: [amd64]
compression: lzo

license: MIT

website: https://github.com/mamantoha/ydokey
issues: https://github.com/mamantoha/ydokey/issues
source-code: https://github.com/mamantoha/ydokey.git

layout:
  /usr/include/linux/input-event-codes.h:
    bind-file: $SNAP/usr/include/linux/input-event-codes.h

apps:
  ydokey:
    command: bin/ydokey

parts:
  ydokey:
    plugin: crystal
    source: ./
